#Irei utilizar a conexão default da gem <pg>
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 2319
  host: localhost
  port: 5432

development:
  <<: *default
  database: to_do_list_rails_development

test:
  <<: *default
  database: to_do_list_rails_test

production:
  <<: *default
  database: to_do_list_rails_production
  username: to_do_list_rails
  password: <%= ENV["TO_DO_LIST_RAILS_DATABASE_PASSWORD"] %>
